name: fk_common_ui
description: Package for Filip Kowalski's projects
version: 0.0.1
author: Filip Kowalski
homepage: filippkowalski.com
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
